# Assignments {.unnumbered}

*As part of this course, starting from Lab 2, there will be a weekly hand in. Here, follows the instructions for creating and handing in course assignments.*

## Assignment Instructions

The assignment will be marked "Group Assignment" with red font in the exercises. In your group, you are to prepare an answer to **just this one question**. Think about reproducibility from the get-go, so include in your assignment, what is needed to re-create your micro-report, e.g. if you're using external data, from where and how did you get it? You will then receive group feedback on your assignment, which you should make sure to go over in your group.

*Please note, that in order to include all elements in a self-contained html file, you will have to use the following YAML-header in your Quarto document:*

```{r}
#| eval: false
#| echo: true
---
title: "Lab 2 Assignment: Group 02"
format:
  html:
    embed-resources: true
editor: visual
---
```

*Or at least one similar, format title and other elements as you see fit, key here is the `html`-format with embedded resources.*

## How to hand in

1. Check that your assignment conforms to the assignment checklist, as defined in the next section
1. Go to [DTU Learn](http://learn.inside.dtu.dk)
1. Find and click your `R for Bio Data Science` course
1. Make sure you are enrolled in the correct group, as defined by the Group Formation Sheet (see the [Getting Started Section](getting_started.qmd))
1. In case groups consists of a mix of BSc. and MSc. students, then enroll under your respective courses
1. Only hand in **one** assignment, meaning either under the BSc. or the MSc. course, **not** both
1. You should hand in the rendered html-file, make sure to compress it to a zip-file prior to upload

## Deadline

- **The deadline for handing in is Thursday 23.59**

## Assignment Checklist

Did you?

1. Match your group number with DTU Learn groups
1. Add Group number, names and student ids?
1. Only answer what is defined as "Group Assignment"
1. Create the assignment using Quarto
1. Modify the YAML-header to ensure encapsulation (see above)
1. Use proper markdown headers as defined by `#`, `##`, `###`
1. Write a few sentences under each section
1. Separate text clearly from code chunks
1. Follow [course code styling](code_styling.qmd)
1. Think about reproducibility with respect to data and libraries?
1. Render to html
1. Compress the html-file to a zip-file, **before** upload to DTU Learn
1. Make sure to download the upload'ed zip-file and check that everything looks right?
