# Getting Started {.unnumbered}

_This section contain essential information for getting up and running for the classes_

## Logging onto Cloud Server

First, make sure you have a working DTU account, either as a student id or employee initials (e.g. PhD-students or postdocs). In this course we will be using a cloud server infrastructure to perform our work. Click below to access the cloud server:

- [R for Bio Data Science Cloud Server](http://teaching.healthtech.dtu.dk/22100/rstudio.php)

Note, that there is a 24h time out on the sessions, meaning that if you logon and forget to sign out, your session will be terminated after 24h.

## Setting up a GitHub account

Prior to class, please go to [GitHub](https://github.com) and setup and account, shouldn't take long. During the registration process you can set up a student account, which will give you additional benefits, including GitHub Pro. In order to get it, you need to use your @dtu.dk email when setting account and select Apply for your GitHub student benefits when asked during the registration process. You'll be then asked to apply for GitHub Student Developer Pack, which will require uploading your student id photo. The process of confirming a student account may take up to a few days (however, it can be almost instantaneous). In the meantime you can already use your free account. Free account should be sufficient for this class, so if you don't want to set up a school account, you don't need to. Please state your GitHub username in this google sheet.

## Class Communication

This course has grown from ~35 students in 2020 to ~150 students in 2023, therefore this term we will be using Piazza for class discussion. The system is highly catered to getting you help fast and efficiently from classmates, the TAs, and myself. Rather than emailing questions to the teaching staff, I encourage you to post your questions on Piazza. If you have any problems or feedback for the developers, email [team@piazza.com](mailto:team@piazza.com).

Find our class signup link at: [https://piazza.com/dtu.dk/fall2023/22100](https://piazza.com/dtu.dk/fall2023/22100) and see the [Intro for Students](https://www.youtube.com/watch?v=tqGummy1Be4) video.

## Group Formation

The backbone of this course is modern collaborative data science and as such "active participation in the group work ... [is an] indispensable prerequisites for exam participation" as stated in the course base. Furthermore, It is **important** that course participants prioritise to be present during classes as the course design is based on student-student interaction in an active learning environment.

Therefore, students will work in groups of 4-5 students. Group formation sheet can be found [here](https://docs.google.com/spreadsheets/d/1MtXCz41uGSnBpJvTARd1TNyqCFYinQxJCEpOwzlBcPo/edit?usp=sharing)

## To do

Each group has to complete the assignment containing information on which data set you selected for the project and a brief text on preliminary project direction (Read “Is this data set ok to use?” below)

Recall from Lab 1:

Important information

## Course Check list

### Before Course starts

- [ ] Setup course pre-evaluation using google forms
- [ ] Groups using sheets, remember to allow edit access, 3-5 members per group
- [ ] Remember to include midterm evaluation
- [ ] Setup RStudio Cloud
- [ ] Notification can be turned on for announcements
- [ ] Book rooms for teaching n students
- [ ] Close post enrollment if nessesary
- [ ] Make a waiting list if nessesary
- [ ] Add TAs to learn
- [ ] Create invitation for lab 10 mini symposium
- [ ] Create overview of enrollment*

* Exporting Classlist/Groups to CSV/Excel: Course admin => Grades => Enter Grades => Export => Deselect all => Export to CSV. [Source](https://learnsupport.dtu.dk/teachers/Export_classlist_or_groups_to_excel_or_csv.php)

### At first session
- [ ] Take role call to see who showed up

### After first session
- [ ] Create groups based google sheet on DTU Learn
- [ ] Invite/add users to RStudio Cloud workspace
- [ ] Write participation email to no-show students

## Notes

- At midway eval, ask if the student are actually spending 5h outside class
- Add intro-to-bioinformatics to pre-requisites
- Assignment are created inside a module, set start-end-dates -> CLICK VISIBILITY IN THE BOTTOM
- My course -> class list -> email class list -> Send email
- Check if added students are also on learn
- List of assignemtns: Course content -> assignments
- Pre-evaluation
- Midterm-evaluation
- Paste in evaluering.dtu.dk link in an announcement to make sure they can find it easily
- Discussions
- Peer-eval?
- Each student need a github token to avoid the API error

## Notes reg. online teaching
- Add TAs to learn
- CSV file -> group rooms at zoom
- At each lab, setup zoom session
- Setup RStudio workspace for students
- Create we-need-input-waiting-list google sheet


Important information

In today's lab you will be introduced to R packages and how to build them. The exercises will give you examples of functions to implement, but you will be given the honor of naming them. "There are only two hard things in Computer Science: cache invalidation and naming things." --- Phil Karlton

Important information

Today will be something completely new! Briefly on shiny: Think of shiny as a way to connect your data to a pointy-clicky interface, so that non-data users may interact with it Before class, create an account on shinyapps.io and link it to your GitHub account Building an app can lead to some headaches if you walk in to it too carelessly. Help yourself by reading the suggested chapters and use the cheatsheets as much as possible.

Important information

Location: Auditorium 32 in building 306 Google doc for audience questions can be found here
