# Lab 10 Project Startup & Industry Talks {.unnumbered}

## Schedule

- 08.00 - 08.15: [Recap of Lab 9](https://raw.githack.com/r4bds/r4bds.github.io/main/recap_lab10.html)
- 08.15 - 08.45: [Introduction to Project Period and Exam](https://raw.githack.com/r4bds/r4bds.github.io/main/lecture_lab10.html)
- 08.45 - 09.00: Break
- 09.00 - 12.00: [Mini Symposium](#sec-symposium)

## Mini Symposium: Applications of R for Bio Data Science in Industry {#sec-symposium}

*This mini symposium on Applications of R for Bio Data Science in Industry aims to give students a glimpse into how modern bio data science is transforming value creation in the pharmaceutical industry and healthcare sector.*

### 2024

#### Companies Represented

- [Gubra](https://www.gubra.dk)
- [QIAGEN](https://www.qiagen.com/dk/product-categories/informatics-and-data)
- [UCPH Center for Health Data Science](https://heads.ku.dk)
- TBA

#### Symposium Programme

- [Abril Diosdado Hernández](https://www.linkedin.com/in/abrildh/), Associate Research Scientist, [Gubra](https://www.gubra.dk)
- [Ruth Stoney ](https://www.linkedin.com/in/ruth-stoney-19b603b9/), Senior Field Applications Scientist, [QIAGEN](https://www.qiagen.com/dk/product-categories/informatics-and-data)
- [Helene Wegener](https://www.linkedin.com/in/helene-wegener-75b589230/), Junior Data Scientist, [UCPH Center for Health Data Science](https://heads.ku.dk)
- TBA

### 2023

#### Companies Represented

- [Clinical Microbiomics](https://clinical-microbiomics.com)
- [Gubra](https://www.gubra.dk)
- [Lundbeck](https://www.lundbeck.com/global)
- [Novo Nordisk](https://www.novonordisk.com)
- [ZS](https://www.zs.com)

#### Symposium Programme

- 09.00 – 09:25: "Harnessing R Packages for Microbiome Analysis and Reporting" by [Maria Novosolov](https://www.linkedin.com/in/maria-novosolov/), Data Scientist, Clinical Microbiomics
- 09.25 – 09:50: "Plotly and Shiny apps for exploratory analysis of transcriptomics data" by [Christina Bligaard Pedersen](https://www.linkedin.com/in/bligaard/), Senior Bioinformatician & [Mikhail Osipovitch](https://www.linkedin.com/in/mikhailos/), Lead Bioinformatician, ZS
- 09.50 – 10:00: Break
- 10.00 – 10:25: "An ADA monitoring tool developed with Rshiny" by [Carlotta Porcelli](https://www.linkedin.com/in/carlottap/),  Senior Statistical Programmer, Novo Nordisk
- 10.25 – 10:50: "The R in R&D efficiency" by [Victor A. O. Carmelo](https://www.linkedin.com/in/victor-carmelo-8ab329155/), Principal Bioinformatician, Lundbeck
- 10.50 – 11:00: Break
- 11.00 – 11:25: "From data analysis to infrastructure: A journey with R" by [Sebastian Tølbøl Thrane](https://www.linkedin.com/in/sebthr/), Senior Scientist, Gubra
- 11.25 – 11:50: "The long and winding road to use R in a pharmaceutical company" by [Claus Dethlefsen](https://www.linkedin.com/in/clausdethlefsen/), Statistical Director, Novo Nordisk
- 11.50 – 12:00: Symposium round-off

### 2022

#### Companies Represented

- [Abzu](https://www.abzu.ai)
- [Bristol Myers Squibb](https://www.bms.com)
- [Clinical Microbiomics](https://clinical-microbiomics.com)
- [Novo Nordisk Bioinformatics](https://www.novonordisk.com)
- [Novo Nordisk Biostatistics](https://www.novonordisk.com)
- [Steno Diabetes Center Copenhagen](https://www.sdcc.dk)

#### Speaker List

- [Andrea Marquard](https://www.linkedin.com/in/andreamarquard/), Head of Data Science and Automation, Clinical Microbiomics: "How we use internal R packages, and why you should learn to make one"
- [Anders Gorst-Rasmussen](https://www.linkedin.com/in/anders-gorst-rasmussen-50bb732/), Statistical Director, Novo Nordisk Biostatistics, Novo Nordisk: "How we use R in Novo Nordisk Biostatistics"
- [Anne-Mette Bjerregaard](https://www.linkedin.com/in/anne-mette-bjerregaard-821b8295/), Senior Scientist in Computational Biology, Novo Nordisk: "The Evolution of a Computational Biologist"
- [Sam Demharter](https://www.linkedin.com/in/demharter/), Bioinformatics Specialist, Abzu: "Explainable AI in Precision Medicine - Closing the Loop from Patient to Drug"
- [Lykke Pedersen](https://www.linkedin.com/in/lykkepedersen/), Head of RNA Therapeutics, Abzu: "Explainable AI in Precision Medicine - Closing the Loop from Patient to Drug"
- [Simon Papillon-Cavanagh](https://www.linkedin.com/in/simon-papillon-cavanagh-3435b9108/), Principal Scientist, Bristol Myers Squibb (USA): "A Career Built on Mistakes"
- [Sofie Olund Villumsen](https://www.linkedin.com/in/sofie-olund-villumsen-044ba8147/), Bioinformatician, Steno Diabetes Center Copenhagen: "Using R for Data Analysis in Clinical Studies"
- [Tarun Veer Singh Ahluwalia](https://www.linkedin.com/in/ahluwalia0679/), Assoc. Prof., Steno Diabetes Center Copenhagen: "Using R for Data Analysis in Clinical Studies"

### 2021

#### Companies Represented

- [Abzu](https://www.abzu.ai)
- [ALK](https://www.alk.dk/)
- [Chr. Hansen](https://www.chr-hansen.com/en)
- [Lundbeck](https://lundbeck.com/global)
- [Novozymes](https://www.novozymes.com/en)
- [TeraData](https://www.teradata.com/About-Us/Contact/Denmark)

#### Speaker List

- [Samuel Demharter](https://www.linkedin.com/in/demharter/), Senior Bioinformatician, Abzu
- [Lykke Pedersen](https://www.linkedin.com/in/lykkepedersen/), Senior Bioinformatician, Abzu
- [Marie-Catherine Le Bihan](https://www.linkedin.com/in/marie-catherine-le-bihan-459b6351/), Senior Data Scientist, Chr. Hansen
- [Thomas Strantzl](https://www.linkedin.com/in/thomas-stranzl-b87b202b/), Head of Bioinformatics, ALK
- [Maria Dalby](https://www.linkedin.com/in/maria-dalby-91334b67/), Postdoctoral Researcher, Lundbeck
- [Thomas Poulsen](https://www.linkedin.com/in/thpoulsen/), Science Manager, Novozymes
- [Mikkel Freltoft Krogsholm](https://www.linkedin.com/in/mikkelkrogsholm/), Team lead, Senior Data Scientist, TeraData
