---
title: "Pre Course Questionnaire"
author: "Leon Eyrich Jessen"
format:
  revealjs:
    embed-resources: true
    theme: moon
    slide-number: c/t
    width: 1600
    height: 900
    mainfont: avenir
    logo: images/r4bds_logo_small.png
    footer: "R for Bio Data Science"
---

<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Student Composition
```{r}
library("tidyverse")
library("broom")

d <- read_csv(file = "data/01_pre_course_survey_2024.csv") |> 
  select(
    x1 = `What is your current activity?`,
    x2 = `Prerequisites - Have you completed mentioned courses or equivalent prior to this course?`,
    x3 = `How many years of programming (language irrelevant) experience do you have?`,
    x4 = `How many years of base R-programming experience do you have?`,
    x5 = `How many years of tidyverse R-programming experience do you have?`,
    x6 = `Have you previously worked with any kind of data analysis?`) |> 
  filter(x1 %in% c("Bachelor student","Master Student","PhD Student","Postdoc","Industry"),
         str_starts(string = x2, pattern = "\\d{5}"),
         str_starts(string = x6, pattern = "Yes|No"))

d <- d |>
  mutate(id = row_number()) |> 
  relocate(id) |> 
  # mutate(dummy = 1) |>
  # pivot_wider(id_cols = everything(),
  #             names_from = x1,
  #             values_from = dummy,
  #             values_fill = 0) |> 
  separate_rows(x2, sep = ", ") |> 
  filter(str_starts(x2, "\\d{5}")) |> 
  mutate(dummy = 1) |>
  pivot_wider(id_cols = everything(),
              names_from = x2,
              values_from = dummy,
              values_fill = 0) |> 
  separate_rows(x6, sep = ", ") |> 
  filter(str_starts(string = x6, pattern = "in|No")) |> 
  mutate(dummy = 1) |>
  pivot_wider(id_cols = everything(),
              names_from = x6,
              values_from = dummy,
              values_fill = 0)
d_pca_obj <- d |>
  select(-id, -x1) |>
  prcomp(center = TRUE, scale. = TRUE)
d_pca_obj_aug <- d_pca_obj |> 
  augment(d)

lbl <- d_pca_obj |>
  tidy("eigenvalues") |>
  mutate(lbl = str_c("PC", PC, ", Variance Explained = ",
                     round(percent*100,1), "%"))

d_pca_obj_aug |> 
  ggplot(aes(x = .fittedPC1,
             y = .fittedPC2,
             fill = factor(x5))) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  stat_ellipse(aes(colour = factor(x5))) +
  geom_point(pch = 21, colour = "black", size = 4, alpha = 0.5) +
  labs(title = "R for Bio Data Science, Student Composition",
       x = lbl$lbl[1],
       y = lbl$lbl[2],
       fill = "Tidyverse\nExperience",
       colour = "Tidyverse\nExperience") +
  theme_minimal()
```



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
# Is there any specific area of bio-research you would like to see covered?



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## General Bioinformatics & Data Analysis:

- General interest in bioinformatics.
- Comfortable handling different types of biological data in R.
- How to work with data and make it easier to analyze.
- Visualizations of big data.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Genetics & Genomics:

- Genetics, Genomics, and Evolution.
- Transcriptomics, Metagenomics, Genomic data analysis, and RNA-seq.
- Single cell omics, Bulk RNA-seq data manipulation.
- Gene expression data analysis in R.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Disease & Medical Research:

- Personalized medicine and precision medicine.
- Research related to specific diseases: obesity, cancer, autoimmune diseases, infectious diseases.
- Drug design, clinical drug trials, and drug trial data analysis.
- Analysis of complex cancer patient data.




<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Immunology & Microbiology:

- Immunology, especially related to MHC, neoantigens, antibodies, and antigens.
- Clinical research in R related to immunology.
- Gut microbiome, Microbiome studies on cancer, and Microbiologic studies.
- Immune response bio-research and immune system or stem cells.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Advanced Computational Techniques:

- Predictive modeling and visualizations of complex networks/pathways.
- Deep learning in R and Artificial Intelligence.
- Analysis of peptide sequencing via mass spec (TD-search and de novo).



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Specific Bio-research Topics:
- Food-related research.
- Ecology.
- Plastic degradation by microorganisms or enzymes.
- CO2 capture by microorganisms.
- Mass screening and patient profiling, especially for cancer.
- LC-MS data, peptide prediction from proteins.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Others:

- Some students have expressed that they are open to any topic or aren't particularly focused on a specific area.
- A few are excited about the course in general and don't have specific preferences.
- There's interest in the integration of bioinformatics with scientific articles and hospital data.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
# Briefly, what are your general expectations to this course?



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## R Proficiency:

- Many students wish to gain or improve proficiency in using R for data analysis.
- There's an emphasis on understanding the R environment, syntax, and packages.
- Some students are already familiar with R and wish to polish and expand their skills, while others are complete beginners hoping to grasp the basics.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Bioinformatics and Biology Application:

- Many students want to learn how to apply R specifically to biological and bioinformatic datasets.
- They expect to work with real-life bio data and learn how to handle and analyze data relevant to their bio studies.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Data Visualization & Manipulation:

- Students are keen to learn about data visualization and manipulation in R.
- They are interested in using R for creating plots, visualizations, and handling various data types.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Practical Skills for Future Application:

- Several students hope the course will prepare them for future projects, research, or roles that require data analysis.
- Some students are interested in using the skills they gain in this course for their thesis or future studies.
- A few want to be able to transfer the knowledge they gain to other programming languages, like Python.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Data Analysis Techniques:

- Students wish to learn about different data analysis methods, including statistics, RNA sequencing data processing, etc.
- They hope to understand how to organize, clean, and interpret data.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Tool and Package Familiarity:

- Some students want to familiarize themselves with specific R packages, like tidyverse.
- There's an interest in learning how to utilize GitHub for shared programming.
- Several mention wanting to know how to use specific tools for data analysis, such as data wrangling and lab notebook style coding.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Learning Environment:

- A few students mentioned hoping for a structured or gradual introduction, especially for those without prior knowledge.
- Some have heard from past students and have expectations based on word-of-mouth.
- A couple of students are concerned about the timing and structure of the exam.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Miscellaneous:

- There are mentions of topics like the application of R in various biological datasets, multiomics, and genetics.
- Some are looking forward to learning how to plan scientific studies or adjust chosen methods.
- A few students don't have specific expectations, while others hope for a challenging but rewarding experience.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
# Summary



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## Alignment of Expectations

- Key criteria for succes is that we agree on the content of this course
- Luckily, much of what is mentioned is part of this course
- However, if we were to cover all of the mentioned aspects, that would basically be an entire bioinformatics education



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## This course

- Practical Application: Equip students with hands-on bio data science skills, emphasizing on transforming messy datasets to clean, structured ones, and performing insightful data analyses.
- Tools & Platforms: Utilize Tidyverse R, RStudio IDE, Quarto reporting, git/GitHub, and other specific tools such as dplyr, ggplot, and shinyapps.io for comprehensive bio data science tasks.
- Reproducibility & Collaboration: Stress on the importance of reproducible data analysis and effective collaboration in bio data science projects using Tidyverse R and git/GitHub.
- Broad Skill Set: Train students to perform basic statistical tests, create R packages, design Shiny apps, employ Large-Language-Model (LLM) technology like chatGPT, and more.
- Project Analysis & Presentation: Guide students to assess and critique bio data science projects on method choices and data communication, and organize & present their own results in dynamic Quarto reports.



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
## This course - In other words

- Creates the foundation for you to explore the multitude of bioinformatics subjects
- Gives you concrete skills to handle (almost) any kind of bio data
- Trains your collaborative and communicative meta skills



<!--# ---------------------------------------------------------------------- -->
<!--# SLIDE ---------------------------------------------------------------- -->
<!--# ---------------------------------------------------------------------- -->
# Tag along and you'll have fun and learn a ton!
