# Lab 7: Scripting in a Reproducible and Collaborative Framework using GitHub via RStudio {.unnumbered}

#### STOP: Section not yet completed!

Package(s)

- [usethis](https://usethis.r-lib.org)
- [git](https://git-scm.com/) (Actually not an R-package this time)

## Schedule

- 08.00 - 08.15: Recap of midway evaluation and exercises from last lab
- 08.15 - 08.30: Assignment walk-through
- 08.30 - 09.00: Introduction to Lab
- 09.00 - 09.15: Break
- 09.00 - 12.00: Exercises

## Learning Materials

_Please prepare the following materials_

- Book: [Happy Git and GitHub for the useR](https://happygitwithr.com/) -- Read chapters 1 (intro), 20 (basic terms), 22 (branching), 23 (remotes). Do not pay much attention to syntax of specific commands, because we are not going to use them during the exercises, focus on the idea.
- Book: [Introduction to Data Science - Data Analysis and Prediction Algorithms with R by Rafael A. Irizarry: Chapter 40 Git and GitHub](https://rafalab.github.io/dsbook/git.html) -- Some of the information here is redundant with the previous book, but very important thing is a visualization of basic git actions and screenshots of how to perform them using RStudio.
- Video: [RStudio and Git - an Overview (Part 1)](https://www.youtube.com/watch?v=KjLycV1IWqc) -- Basic git concepts, for those who prefer listen rather than read. Books, however, contain more information.
- Video: [How to use Git and GitHub with R](https://www.youtube.com/watch?v=kL6L2MNqPHg) -- Basic operating on git in RStudio. Complementary to second book. You can skip to 2:50, we are not going to link to git manually either way.

## Learning Objectives

_A student who has met the objectives of the session will be able to:_

- Explain why reproducible data analysis is important
- Identify associated relevant challenges
- Explain replicability versus reproducibility
- Describe the components of a reproducible data analysis
- Use RStudio and GitHub (git) for collaborative bio data science projects
